<?php
$first_array   = array(
    'page'     => $this->first,
    'order_by' => $order_by,
    'order'    => $order,
);
$previous_array = array(
    'page'     => $this->previous,
    'order_by' => $order_by,
    'order'    => $order,
);
$page_array    = array(
    'order_by' => $order_by,
    'order'    => $order,
);
$next_array    = array(
    'page'     => $this->next,
    'order_by' => $order_by,
    'order'    => $order,
);
$last_array    = array(
    'page'     => $this->last,
    'order_by' => $order_by,
    'order'    => $order,
);
(!empty($search_by)) ? $search_query = $search_by:$search_query='';

?>
<?php if ($this->pageCount): ?>
<div>
         <ul class="pagination">
             <!-- Previous page link -->
             <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction,$first_array,array('query'=>$search_query)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction,$previous_array, array('query'=>$search_query)); ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php $page_array['page'] = $page; ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>>
                    <a href="<?php echo $this->url($pageAction,$page_array,array('query'=>$search_query)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction,$next_array,array('query'=>$search_query)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction,$last_array,array('query'=>$search_query)); ?>">&raquo;</a></li>

         </ul>
     </div>
 <?php endif; 